# Generated by Django 5.1.15 on 2026-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_data_assign_challenge_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=60, help_text='Minimum percentage score to pass this challenge (0-100).'),
        ),
    ]
