# Generated by Django 5.1.15 on 2026-09-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationread'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationread',
            new_name='notificatio_user_id_5919d8_idx',
            old_name='notifications_user_notif_idx',
        ),
    ]
