# Generated by Django 5.1.15 on 2026-09-01 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_notifications_user_notif_idx_notificatio_user_id_5919d8_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_4e3567_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_is_read_3a06ff_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
    ]
