# Generated by Django 5.1.15 on 2026-09-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_approvedstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
