# Generated by Django 5.1.15 on 2026-09-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_questions_q_categor_123456_idx_questions_q_categor_f1803c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option_index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
